### ISSUE TITLE
Typo on lecture 2, slide 18

### ISSUE THREAD

**Issue by dscardoso** [irudik/aem6510#1]
Hey Ivan,

A student had a question about this slide and I think there is a typo on the second equation in the Labor Supply FOCs. It should have lambda_z, not lambda_x. It's line 405 of the Rmd file. Would you like me to fix it?

Thanks!

**Comment by irudik** [comment]
Thanks Diego, yeah that looks like a typo. Can you go ahead and fix it? Thanks.

**Comment by dscardoso** [comment]
Hey Ivan, I fixed the typo in the source code but I'm having a problem compiling the new slides. I did not have xaringan and xaringanExtra; the new version I installed changed the syntax and made the command "style_panelset" deprecated. I can't seem to force backward compatibility. I kept this command and hid the warnings, but the slides with tabs are built with weird dimensions.

I'm afraid if I change to the new syntax I may break the code on your end and make it inconsistent with other lectures. Can you please pull the code and knit the html on your end?

**Comment by irudik** [comment]
Ah thanks. Must have changed that very recently. I'll just keep it with the old version for now.
